---

- name: Install epel from remote repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install remi from remote repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    # update_cache: yes
  with_items:
  - git-core