---

- name: Enable HTTP
  firewalld:
    service: http
    permanent: true
    zone: public
    state: enabled

- name: Enable HTTPS
  firewalld:
    service: https
    permanent: true
    zone: public
    state: enabled

- name: Enable SSH
  firewalld:
    service: ssh
    permanent: true
    zone: trusted
    state: enabled
