---
- name: Ensure deploy directory is present
  file:
    dest: /var/www/
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- name: Clone repository
  git:
    dest: /var/www/test
    repo: https://tmukherjee13@bitbucket.org/tmukherjee13/test.git
    update: no
    accept_hostkey: True
  become: yes
  become_user: www-data
  register: cloned
