# ./ansible-nginx/tasks/install_nginx.yml
 
- name: NGINX | Installing NGINX
  apt:
    pkg: nginx
    state: latest
    update-cache: true
 
- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
