---
- name: start php
  service: 
    name: php-fpm
    state: started

- name: reload php
  service:
    name: php-fpm
    state: reloaded

- name: restart php
  service:
    name: php-fpm
    state: restarted